---
abstract: 'get titles of web pages'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-GetPageTitle
provides:
  WWW::GetPageTitle:
    file: lib/WWW/GetPageTitle.pm
    version: 0.0104
requires:
  Class::Data::Accessor: 0.04001
  HTML::Entities: 1.35
  LWP::UserAgent: 2.036
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0104
